// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkjfeqtapyzhgcxyxbvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZramZlcXRhcHl6aGdjeHl4YnZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDU2MzQsImV4cCI6MjA2NjYyMTYzNH0.pefONbBL8g_EEMleGK7JJ1CBvBzArkmY-A2KjOzA6O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);